Hw02 express
DemiGGV/nodejs-homework-API pull request #1
Opened 2023-08-13 14:43 UTC by DemiGGV

2 ДЗ. Перевірте, будь ласка!

2023-08-13 18:05 UTC, ceREAL133 requested changes

2023-08-13 18:05 UTC, ceREAL133 commented on schemas/contact.js
> +  email: Joi.string().required(),
You should validate email and phone properly

2023-08-13 19:00 UTC, DemiGGV commented on schemas/contact.js
> +  email: Joi.string().required(),
Fixing on next commit

2023-08-14 08:42 UTC, ceREAL133 approved these changes

2023-08-14 09:07 UTC, merged